import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Adib's Portfolio",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
